---

- name: Ensure systemd-networkd configuration files exist
  become: true
  vars:
    # Profiles to iterate over. Using a single looped task is more performant
    # than multiple tasks.
    all_files:
      - type: link
        files: "{{ systemd_networkd_link | dict2items }}"
      - type: netdev
        files: "{{ systemd_networkd_netdev | dict2items }}"
      - type: network
        files: "{{ systemd_networkd_network | dict2items }}"
  template:
    src: "systemd_networkd_config.j2"
    dest: "/etc/systemd/network/{{ item.1.key }}.{{ item.0.type }}"
    owner: root
    group: systemd-network
    mode: 0640
  loop: "{{ query('subelements', all_files, 'files') }}"
  loop_control:
    label:
      type: "{{ item.0.type }}"
      name: "{{ item.1.key }}"
  notify: restart systemd-networkd

- name: Manage nsswitch configuration
  become: true
  template:
    src: "nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: 0644
  when: systemd_networkd_manage_nsswitch_config

# vim: set ts=2 sw=2:
