---

- name: copy .link profiles
  become: true
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.link"
    owner: root
    group: systemd-network
    mode: 0640
  loop: "{{ systemd_networkd_link | dict2items }}"
  notify: restart systemd-networkd

- name: copy .netdev profiles
  become: true
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.netdev"
    owner: root
    group: systemd-network
    mode: 0640
  loop: "{{ systemd_networkd_netdev | dict2items }}"
  notify: restart systemd-networkd

- name: copy .network profiles
  become: true
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.network"
    owner: root
    group: systemd-network
    mode: 0640
  loop: "{{ systemd_networkd_network | dict2items }}"
  notify: restart systemd-networkd

# vim: set ts=2 sw=2:
